name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "bnsceo@gmail.com"
          git config --global user.name "Anderson-s-Projects"

      - name: Deploy to GitHub Pages
        run: npx gh-pages -d dist -r "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Anderson-s-Projects/anderson-portfolio.git"
