name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build the project
        run: npm run build

      # Configure Git user
      - name: Set up Git user
        run: |
          git config --global user.email "bnsceo@gmail.com"
          git config --global user.name "Anderson Paulino"

      # Deploy to GitHub Pages with proper authentication
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "bnsceo@gmail.com"
          git config --global user.name "Anderson Paulino"
          npx gh-pages -d dist -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Anderson-s-Projects/anderson-portfolio.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
